version: "3.9"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose: 
      - "5252"
  
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    expose:
      - "9000"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
